allowBuilds:
  core-js: false
  msw: true
  sharp: true
  tree-sitter: set this to true or false
  tree-sitter-bash: set this to true or false
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
